GET http://localhost:8080/users

###

PUT http://localhost:8080/users
Content-Type: application/json

{
  "login": "doloreUpdate",
  "name": "est adipisicing",
  "id": 4,
  "email": "mail@yandex.ru",
  "birthday": "1976-09-20"
}

###
PUT http://localhost:8080/users/6/friends/8
###
POST http://localhost:8080/films
Content-Type: application/json

{
  "name": "Name",
  "description": "Descrition",
  "releaseDate": "1980-03-25",
  "duration": 200,
  "mpa": {
    "id": 10
  }
}
###
POST http://localhost:8080/users
Content-Type: application/json

{"name":"Molly oysle","login":"APbUecrJ4A","email":"Stefsaie_Farrell74@gmail.com","birthday":"2000-06-05"}
###
PUT http://localhost:8080/users/1/friends/2
###
GET http://localhost:8080/users/1/friends